name: Test Case - Damn Vulnerable NodeJS Application (DVNA)

on:
  # push:
  workflow_dispatch:

env:
  # nightvision app create -n dvna-local
  # nightvision target create -n dvna-local -u http://127.0.0.1:9090
  # nightvision auth playwright create -n dvna-local -u http://127.0.0.1:9090
  # nightvision scan -t dvna-local -a dvna-local
  NIGHTVISION_TOKEN: ${{ secrets.NIGHTVISION_TOKEN }}
  NIGHTVISION_TARGET: dvna-local
  NIGHTVISION_APP: dvna-local
  NIGHTVISION_AUTH: dvna-local
  
jobs:
  test:
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: (1) Clone Code
        uses: actions/checkout@v3
      
      - name: (2) Install NightVision
        run: |
            wget -c https://downloads.nightvision.net/binaries/latest/nightvision_latest_linux_amd64.tar.gz -O - | tar -xz; sudo mv nightvision /usr/local/bin/
                    python -m pip install semgrep --user

      - name: (3) Start the app
        run: docker run --name dvna -p 9090:9090 -d appsecco/dvna:sqlite
        # docker-compose up -d; sleep 10

      - name: (4) Scan the API
        run: nightvision scan -t ${NIGHTVISION_TARGET} -a ${NIGHTVISION_APP} > scan-results.txt

